services:
  postgresql:
    image: postgres:16
    container_name: framework_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: framework_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    restart: unless-stopped
    networks:
      - framework_network
    volumes:
      - postgresql_data:/var/lib/postgresql/data

networks:
  framework_network:
    driver: bridge

volumes:
  postgresql_data: